/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import uos.gui.GUISystem;


import static org.junit.Assert.*;

import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.Utilities;

import java.awt.*;
import java.awt.event.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}

