/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import uos.file.FileSystem;
import uos.parse.PMethod;

import static org.junit.Assert.*;

import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.Utilities;

import java.awt.*;
import java.awt.event.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	JFileChooser jFileChooser = new JFileChooser(){
    		    		
    	};
    	
    	jFileChooser.setDialogTitle("Save File");
    	jFileChooser.setCurrentDirectory(new File("."));
    	jFileChooser.setSelectedFile(new File("Queue") );
    	jFileChooser.setDialogType( JFileChooser.SAVE_DIALOG );
    	jFileChooser.setFileFilter( new FileFilter() {
			@Override
			public String getDescription() {
				return "text files";
			}
			
			@Override
			public boolean accept(File f) {
				if( f.isDirectory() ) return true;
				
				if( f.getName().substring(f.getName().lastIndexOf('.') + 1 ).equals("txt") )
					return true;
				else return false;
			}
		});
    	
    	int retVal = jFileChooser.showSaveDialog(null);
    	    	
    	if( retVal == JFileChooser.APPROVE_OPTION ) {
    		File selectedFile = jFileChooser.getSelectedFile();
    		System.out.println(selectedFile.getName());
    	}
    	
    }
}

