/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import uos.parse.PMethod;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	String str = "if( ( last + 1 ) % == first  )\n" +
    			"return true;\n" + "else return false;";
    	System.out.println(str);
    	if( str.contains("firs!!") )
    		System.out.println("first!!!!");
    }
}
